
OPTIONS_UNSET_FORCE=    DOCS EXAMPLES INFO MANPAGES NLS ENCODINGS PLUGINS STATIC

MAKE_JOBS_NUMBER:=      ${:!sysctl -n hw.ncpu!:}

CFLAGS+=                -O2 -pipe
CXXFLAGS+=              -O2 -pipe
