
alias top="htop"

alias ls="ls -F --color=always"
alias ll="ls -sailF"
alias .="source"
alias h="history 1"

# alias gemini="gemini --model gemini-3-flash-preview"
alias gc="gemini --model gemini-3-flash-preview --yolo \
	-p 'Check \`git diff HEAD\`, commit changes, no co-author information' \
"
export LC_ALL=en_US.UTF-8
export LC_CTYPE=zh_CN.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export COLORTERM=truecolor

# rust env
export CARGO_GIT_FETCH_WITH_CLI=true

# golang env
# export GOPROXY=https://goproxy.cn
# export GOPRIVATE=github.com/<YOUR_PRIVATE_REPO>/* # check the `.netrc` file also
export GOPATH=~/.go

PATH=${HOME}/.cargo/bin:${HOME}/go/bin:${HOME}/.local/bin:/usr/local/bin:/usr/local/sbin:$PATH
export PATH=${PATH#*:$HOME/.cargo/bin:$HOME/go/bin:${HOME}/.local/bin:/usr/local/bin:/usr/local/sbin:}

export HISTSIZE=2000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

export EDITOR=vim
export EIX_LIMIT_COMPACT=0

# enable auto-completion
autoload -U compinit
compinit
# completion style
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

# load prompt theme
autoload -U promptinit
promptinit

# other nice themes: gentoo, walters, adam2
prompt clint
# prompt redhat

# vcs_info for git branch display
autoload -Uz add-zsh-hook vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats '(git)-[%b]-'
add-zsh-hook precmd vcs_info
setopt prompt_subst

# custom platform display: [amd64/freebsd-14.4]
local _p_plat="[%F{cyan}${MACHTYPE}/freebsd-$(uname -r | cut -d- -f1)%F{red}]"
PROMPT="[%F{cyan}%D{%a %y/%m/%d %R %Z}%F{red}][%F{green}%l%F{red}]${_p_plat}
%F{red}{%F{green}%n@%m%F{white}:%F{yellow}%~%F{red}}
%fzsh %B%h%b %(?..[%?] )\${vcs_info_msg_0_}%B%#%b "

# ignore duplicate history entries
setopt hist_ignore_all_dups

set -o vi
